### ISSUE TITLE
Adding "title" Option Like "subtitle" for easier usage

### ISSUE THREAD

**Issue by DinaKhAhmed** [bootsoon/ng-circle-progress#1]
I needed to Have Custom title for Each Dynamically generated chart, without needing to implement a callback function using [titleFormat] option.
to work with my code
```
<div class="col-md-4" *ngFor='let usage of usages,let i = index'>
                <div class="circle-progress">
                        <div class="circle-radius hide" ></div>				
                        <circle-progress 
                        [percent]="usage.usagePercentage"
                        [outerStrokeColor]="usage.type"
                        [backgroundStroke]="usage.type"
                        [titleColor]="usage.type"
                        [subtitleColor]="usage.type"	
                        [unitsColor]="usage.type"
                        [space] = "0"	
                        [showUnits]="false"
                        [animateTitle]="false"
                        [title]="usage.englishDisplayName"
                        [subtitle]="usage.englishSubName"
>
                        </circle-progress>
                    </div>
                    <p class="text-center text-primary"><strong>{{usage.usedAmount}} {{'AccountOverview.of' |translate}} {{usage.initialTotalAmount}} 
                        <small *ngIf="this.translationService.language=='Ar'">{{usage.measureUnitArName}}</small><small *ngIf="this.translationService.language=='En'">{{usage.measureUnitEnName}}</small></strong> <em class="icon-{{usage.mesaureUnitId}}"></em></p>					
                    
        </div>
```
I managed to Achieve that by editing in the plugin files which is a terrible thing to do of course,
Is there a possibility that you support this feature soon?
@bootsoon 
I have attached the edited files FYI.

 
[ng-circle-progress Modified Files.zip](https://github.com/bootsoon/ng-circle-progress/files/1431148/ng-circle-progress.Modified.Files.zip)

**Comment by DinaKhAhmed** [comment]
@bootsoon I've applied a fix for this issue here 
https://github.com/DinaKhAhmed/ng-circle-progressWithTitleOption as I wasn't able to push this new Banch created in here and I've tested it on my Current project and its working perfectly.

Percentage is Displayed when no title is provided.

**Comment by bootsoon** [comment]
@DinaKhAhmed A 'title' is definitely necessary. Thanks for your suggestion. I'll fix it in a week.

**Comment by bootsoon** [comment]
@DinaKhAhmed Sorry, I cannot find any code in https://github.com/DinaKhAhmed/ng-circle-progressWithTitleOption . Where is the './src' folder?

Please update to 0.9.6. I've added a 'title' option which defaults to 'auto', meaning 'percentage is displayed automatically'.

```
<div class="col-md-4" *ngFor='let usage of usages,let i = index'>
    <div class="circle-progress">
        <div class="circle-radius hide" ></div>				
        <circle-progress 
            [title]="usage.englishDisplayName"
            [showUnits]="false">
        </circle-progress>
    </div>
</div>
```

**Comment by bootsoon** [comment]
@DinaKhAhmed Here is my modification:

```
// 0.9.6
(this.options.titleFormat !== undefined && this.options.titleFormat.constructor.name === 'Function')
          ? this.options.titleFormat(titlePercent) : (this.options.title === 'auto' ? titleTextPercent : this.options.title),
```

```
// 0.9.5
(this.options.titleFormat !== undefined && this.options.titleFormat.constructor.name === 'Function')
          ? this.options.titleFormat(titlePercent) : titleTextPercent,
```

**Comment by DinaKhAhmed** [comment]
@bootsoon I've applied this fix,
Will you please check it if its valid and usable or not?

https://github.com/DinaKhAhmed/ng-circle-progressWithTitleOption

**Comment by DinaKhAhmed** [comment]
@bootsoon  you are a life Saver, Many thanks for your support

**Comment by bootsoon** [comment]
@DinaKhAhmed You're welcome.
