### ISSUE TITLE
lazy true not work

### ISSUE THREAD

**Issue by shomid** [bootsoon/ng-circle-progress#101]
I want to load image is lazy and added `[lazy]="true"` to `circle-progress` tag but not work lazy loading image.

**Comment by bootsoon** [comment]
`lazy` does not work for image loading.

If `lazy` is true, the circle pauses at the last position when it's out of viewport and becomes active again when visible, listening to events of scrolling and window resizing.

![nxqTJAvUdY](https://user-images.githubusercontent.com/20899374/58494075-da633600-81a6-11e9-9c4e-0dca51b3607f.gif)
