### ISSUE TITLE
startFromZero is not works

### ISSUE THREAD

**Issue by jcervant16** [bootsoon/ng-circle-progress#102]
hello, trying to use the startFromZero property with angular 5 and throws error, as if that property did not exist in the interface

**Comment by bootsoon** [comment]
https://bootsoon.github.io/ng-circle-progress/

``` [startFromZero]="true"```

**Comment by jcervant16** [comment]
Hi, I receive the following error when trying to use it. 
![image](https://user-images.githubusercontent.com/26825803/65525337-f5c02280-deb4-11e9-8093-fb30a67d0a54.png)

**Comment by bootsoon** [comment]
`startFromZero` was introduced from version 1.2.0.
