### ISSUE TITLE
MaxPercentage doesn't work

### ISSUE THREAD

**Issue by mchmiele** [bootsoon/ng-circle-progress#107]
When I set maxPercent to 2000 and set Percent to 200, the circle is full. MaxPercent just doesn't affect at all. Whatever value is set to maxPercent, any value set to percent bigger or equal to 100, makes the circle full

**Comment by bootsoon** [comment]
@mchmiele maxPercentage isn't a total and percent always represents the actual progress. E.g. If percent is set to 50, the circle is always half full no matter how many maxPercent is.
maxPercent cause the default title show a "+" at the right side of the number if it's less than the percent. Always set percent to 100 if you want your circle always be completed. Use titleFormat callback to show something else as title.

Ref #25 [Max percent lower than 100 issue](#25 )
