### ISSUE TITLE
outer stroke won't display in Safari browser

### ISSUE THREAD

**Issue by khSnOw** [bootsoon/ng-circle-progress#111]
The outer stroke of the circular progress component works perfectly with all browsers, except safari!

**Comment by tijnbarthen** [comment]
@khSnOw We are having the same issue here. Did you already find a solution?

**Comment by lampham2505** [comment]
![image](https://user-images.githubusercontent.com/21020492/76062510-6ddc5980-5fb8-11ea-8c4b-39d6c0cd2f3d.png)
It's not working on bootsoon too.

**Comment by khSnOw** [comment]
Hi, sorry for the late reply as a workaround you have to remove the "outerStrokeGradient" in my case this works perfectly.
