### ISSUE TITLE
Builds fail in Angular 9. 

### ISSUE THREAD

**Issue by jlbates** [bootsoon/ng-circle-progress#116]
There are some breaking changes in Angular 9 for libraries. Per the migration docs for Angular 9:

"ModuleWithProviders type without a generic
Some Angular libraries, such as @angular/router and @ngrx/store, implement APIs that return a type called ModuleWithProviders (typically via a method named forRoot()). This type represents an NgModule along with additional providers. Angular version 9 deprecates use of ModuleWithProviders without an explicitly generic type, where the generic type refers to the type of the NgModule. In a future version of Angular, the generic will no longer be optional.

If you're using the CLI, ng update should migrate your code automatically. If you're not using the CLI, you can add any missing generic types to your application manually."

https://angular.io/guide/deprecations#modulewithproviders-type-without-a-generic

<img width="1081" alt="Screen Shot 2020-03-19 at 11 36 16 AM" src="https://user-images.githubusercontent.com/2712938/77091567-bba08b00-69d6-11ea-97a2-44b0d2df6440.png">

**Comment by jlbates** [comment]
I think this change will fix the problem.
https://github.com/bootsoon/ng-circle-progress/pull/117

**Comment by ocsi94** [comment]
+1
error confirmed

**Comment by mannyorozco** [comment]
+1

Can someone verify and merge the open PR please.

**Comment by bootsoon** [comment]
Sorry for late merging.
