### ISSUE TITLE
UTF-8 support

### ISSUE THREAD

**Issue by mokmap** [bootsoon/ng-circle-progress#119]
Hi,

I'm French and I use French special characters. When I use one for units I have a triangle displayed because it doesn't support UTF-8. 

For example if I put the $ sign, it displays fine but if I put the € sign, it doesn't display and I have a triangle instead. 

Can you approach this change? 

Thank you

**Comment by bootsoon** [comment]
@mokmap NgCircleProgress does support UTF-8. I don't know why it doesn't work in your case. Could you post some code or an example like https://stackblitz.com/edit/angular-circle-progress?file=src%2Fapp%2Fapp.module.ts ?
