### ISSUE TITLE
I'm trying to make a 0-10 circle but when I pass [maxPercent]="10" it still defaults to 100.

### ISSUE THREAD

**Issue by shashanksingh324** [bootsoon/ng-circle-progress#120]
I'm trying to make a 0-10 circle but when I pass [maxPercent]="10" it still defaults to 100.

https://stackblitz.com/edit/angular-circle-progress?file=src%2Fapp%2Fapp.module.ts

**Comment by bootsoon** [comment]
@shashanksingh324  `maxPercentage` isn't a total and `percent` always represents the actual progress. E.g. If `percent` is set to 50, the circle is always half full no matter how many  `maxPercent` is. 
`maxPercent` cause the default title show a "+" at the right side of the number if it's less than the  `percent`.  Always set `percent` to 100 if you want your circle always be completed. Use `titleFormat` callback to show something else as title.

https://github.com/bootsoon/ng-circle-progress/issues/9 https://github.com/bootsoon/ng-circle-progress/issues/25
