### ISSUE TITLE
Can't get Title and Subtitle together in centre

### ISSUE THREAD

**Issue by man-oz** [bootsoon/ng-circle-progress#122]
![Screenshot 2020-05-15 at 1 26 54 PM](https://user-images.githubusercontent.com/65391826/82027050-4b01ac00-96b1-11ea-9bf6-2e38b125a4d4.jpg)

As shown in this image the Text tspan element should have y="100" attribute to y="120" can see that working fine in developer tools by changing that manually, but can't make it work other way round. Anyone, Working first time with these elements.
I know that on :
[showUnits]="false"
 [showSubtitle]="false" 
I can get the TITLE in centre but Need that Subtitle too.
![Screenshot 2020-05-15 at 1 40 13 PM](https://user-images.githubusercontent.com/65391826/82027337-b5b2e780-96b1-11ea-9599-19d89e93fdaf.jpg)

**Comment by dineshnirali** [comment]
How to fix this ?
Plz help me out
