### ISSUE TITLE
Progress bar starts from 0 on every update to [percent]

### ISSUE THREAD

**Issue by CD-UNCC** [bootsoon/ng-circle-progress#123]
Please see [stackblitz here](https://angular-ivy-vqrqsu.stackblitz.io)

Why does the progress bar animation going from say 25% to 50% have to start from 0? Why is the animation not animating going from 25 to 50?

[full stackblitz here](https://stackblitz.com/edit/angular-ivy-vqrqsu?file=src%2Fapp%2Fapp.component.html). Just an interval updating percent

**Comment by bootsoon** [comment]
@CD-UNCC set `startFromZero = false`
