### ISSUE TITLE
Please publish latest version to npm.

### ISSUE THREAD

**Issue by DennisAMenace** [bootsoon/ng-circle-progress#127]
The package in the npm repository does not include the fix for ng9, please push the package.

Ref: https://github.com/bootsoon/ng-circle-progress/issues/116

**Comment by Apro123** [comment]
Thank you for this. I thought this project was a gonner. Try this command:
`npm i https://github.com/bootsoon/ng-circle-progress`

**Comment by bootsoon** [comment]
@DennisAMenace @Apro123 

1.6.0 released for  Angular 10 and 9 (>=9.1.0).
