### ISSUE TITLE
Remove click on ng-circle-progress

### ISSUE THREAD

**Issue by paras06** [bootsoon/ng-circle-progress#13]
Hi Team,

When we click on center position of ng-circle-progress component, the progress bar start to load from 0. Is there any property to remove the click event on ng-circle-progress?

Regards,
Paras

**Comment by bootsoon** [comment]
@paras06 Set renderOnClick.

`[renderOnClick]='false'`

in circle-progress.component.ts:

```
  emitClickEvent = (event) => {
    if (this.options.renderOnClick) { this.animate(); }
    this.onClick.emit(event);
  }
```
