### ISSUE TITLE
title and subtitle is not working

### ISSUE THREAD

**Issue by ranavc32** [bootsoon/ng-circle-progress#14]
I tried changing the title by setting to 

```
<circle-progress
  [percent]="85"
  [radius]="100"
  [space]="-10"
  [outerStrokeWidth]="10"
  [innerStrokeWidth]="10"
  [outerStrokeColor]="'#78C000'"
  [innerStrokeColor]="'#C7E596'"
  [animation]="true"
  [animationDuration]="300"    
  [showTitle]="true"
  [title]="UI"
  [subtitle] = "HTML"
  [showUnits]= "true"
></circle-progress>
```

In module,

```
config = {
  "backgroundOpacity": "1",  
  "animateTitle": false,
  "animationDuration": 1000,  
  "showBackground": false,
  "clockwise": true,  
}
```

in Import Array : 

`NgCircleProgressModule.forRoot(this.config),`

Please let me know, if I am missing something 

Thanks 
:)

**Comment by bootsoon** [comment]
Have you defined variable `UI` and `HTML`?

If they are only String, use:

```
  [title]="'UI'"
  [subtitle] = "'HTML'"
```

**Comment by ranavc32** [comment]
In documentation it was mentioned that it accept string value. Thanks It solved the problem.
Keep updating you are doing awesome work. :)

**Comment by bootsoon** [comment]
@ranavc32 

You can bind just a fixed string to a property,

`title="UI"`

or use one-way binding with expression-syntax.

`[title]="'UI'"`
