### ISSUE TITLE
Title is not centered when fontSize params input is changed

### ISSUE THREAD

**Issue by tridungbk2010** [bootsoon/ng-circle-progress#15]
titleFontSize changed from 20(default) to an other size, then Title is not center alignment

**Comment by subahan-appface** [comment]
yes. how to fix this .. can anyone know. please let us know.. thank you

**Comment by bootsoon** [comment]
![titleFontSize 50](https://user-images.githubusercontent.com/20899374/34808928-bd47c808-f6cc-11e7-8435-b66a73e7fc31.png)

@tridungbk2010 @subahan-appface Would you give me more information about this issue?

**Comment by subahan-appface** [comment]
![screen shot 2018-01-11 at 10 16 09 am](https://user-images.githubusercontent.com/13073470/34809054-995177e6-f6b8-11e7-83b7-34cf512925f0.png)
![screen shot 2018-01-11 at 10 16 21 am](https://user-images.githubusercontent.com/13073470/34809055-99916e6e-f6b8-11e7-8936-39d254b5e87a.png)

i have attached screenshots of my code and and circle... please take a look

**Comment by bootsoon** [comment]
OK, I got it. It's not at the center of the circle, and I'll try to fix it. Thank you for your patience.

**Comment by subahan-appface** [comment]
Bro. Have you fixed this ???

**Comment by bootsoon** [comment]
@subahan-appface  I'm working on #15 and #17 and will fix them at the same time.

**Comment by bootsoon** [comment]
@subahan-appface @tridungbk2010 Please update to 0.9.9.

![image](https://user-images.githubusercontent.com/20899374/35483427-bdb7cc9e-047c-11e8-9141-817e0c07c95c.png)

**Comment by subahan-appface** [comment]
Thanks Bro  @bootsoon  .. For fixing this... i have updated to 0.9.9 its working ..
