### ISSUE TITLE
titleFormat to show the title in two line

### ISSUE THREAD

**Issue by abedzaben28** [bootsoon/ng-circle-progress#16]
i have very long title and i want tobreak it to two lines i tried with (but didn't work) :

formatSubtitle = (percent: number) : string => {
    return "11111111111111111111 \n 222222222222222"
  }
and i tried this also 

formatSubtitle = (percent: number) : string => {
    return "11111111111111111111<br/> 222222222222222"
  }

**Comment by bootsoon** [comment]
I don't think you can do this by inserting '\n' or '<br/>' into a SVG <tspan> element. It works in HTML but not in SVG.
