### ISSUE TITLE
When stroke width is 5, then 95% actually covers/fills the full circle instead it should fill 95% of the circle.

### ISSUE THREAD

**Issue by christyfernandes** [bootsoon/ng-circle-progress#160]
@jlbates @ruisebastiao @arturovt @bootsoon 

Please help me to fix this issue.

**Comment by christyfernandes** [comment]
Found a workaround for now

 "outerStrokeLinecap": "butt"

This fills the circle inner stroke precisely to the percentage value up to 99% as expected.

**Comment by bootsoon** [comment]
https://github.com/bootsoon/ng-circle-progress/blob/468251c36223b7bde9a7642e0646023e31192ce4/projects/ng-circle-progress/src/lib/ng-circle-progress.component.ts#L124-L131
