### ISSUE TITLE
long value, units, and subtitles

### ISSUE THREAD

**Issue by abedzaben28** [bootsoon/ng-circle-progress#17]
hi,

i need help to put the unit in new line so the ui could look like:
- line for value its long (timestamp)
- line for unit its long also
- lint for subtitle

thanks in advance

**Comment by bootsoon** [comment]
@abedzaben28 No idea how to make it. Would you please attach a screenshot ?

**Comment by abedzaben28** [comment]
![circle-progressjpg](https://user-images.githubusercontent.com/26892251/34913586-3430d204-f90a-11e7-9fb6-bb58dda57122.JPG)

and i can't make it bigger, there is no enough space, but if we can break it down the title or put the unit in new line will be very helpful here

**Comment by bootsoon** [comment]
I think we might change the code to allow `subtitleFormat` function return an Array object that will be rendered in separate `tspan`s, so does `titleFormat`.

The only catch is all subtitles must be in the same font size. 

@abedzaben28 I can fix it this week if it meets your need.

**Comment by abedzaben28** [comment]
Yes please thatcwill be great

**Comment by abedzaben28** [comment]
@bootsoon  any update ?

**Comment by bootsoon** [comment]
@abedzaben28 Sorry for late, I'm working on a project day and night.  Give me another three days.

**Comment by bootsoon** [comment]
@abedzaben28 Please update to 0.9.9.

![image](https://user-images.githubusercontent.com/20899374/35483445-04ff7dae-047d-11e8-8766-e8bdfa289b52.png)

From 0.9.9,  Array&lt;String&gt; is supported in `title` and `subtitle` and `titleFormat(...)` and `subtitleFormat(...)`.  

```
"title": [
    "working",
    "in",
    "progress"
  ],
```
