### ISSUE TITLE
How we can align the title and subtitle?

### ISSUE THREAD

**Issue by lokendradvs** [bootsoon/ng-circle-progress#177]
Need a margin on top for changing the position.

**Comment by lokendradvs** [comment]
Did you check the issue?

**Comment by bootsoon** [comment]
![image](https://user-images.githubusercontent.com/20899374/156906084-6281b1a4-7f7a-4998-99b7-49cc40432841.png)

There's no margin option.  Pass an array to `title` option.

```
      "title": [
                "working",
                "in",
                "progress"
      ],
```

**Comment by lokendradvs** [comment]
Hi,
Thanks for the reply but the same issue is appearing after trying the values into an array. 

![image](https://user-images.githubusercontent.com/97017375/156913431-f7935c5e-4a97-4b67-acc7-9814db7589e7.png)
![image](https://user-images.githubusercontent.com/97017375/156913462-7127d838-4fb7-45f7-86d3-a955b8001ffc.png)

**Comment by lokendradvs** [comment]
![image](https://user-images.githubusercontent.com/97017375/156913525-264ad181-ef23-4a01-ad1b-d864908d85dd.png)

**Comment by bootsoon** [comment]
```
 "title": [
                "",
                "80%"
      ],
```

**Comment by lokendradvs** [comment]
Ok but if the data is coming dynamically then how it could be happen?

**Comment by bootsoon** [comment]
You can handle it in  `titleFormat` callback.

> **titleFormat** A callback function to format title. It returns a string or an array of string.

```

[titleFormat] = "formatTitle"

// titleFormat callback example
formatTitle = (percent: number) : string => {
  return [ "", percent + "%"]
  }
```

**Comment by lokendradvs** [comment]
Thanks for your reply. But it is overlapping to subtitle 
![image](https://user-images.githubusercontent.com/97017375/157000442-d32f4f44-dea8-4016-9bcc-2ef644f98476.png)

**Comment by bootsoon** [comment]
`titleFormat` is a property in your HTML.
 
```HTML
<circle-progress ...
    [titleFormat]="formatTitle"></circle-progress>
```

`formatTitle` is a function in your TypeScript.

```Typescript
formatTitle = (percent: number)  => {
  return [ "", percent + "%"]
}
```

**Comment by lokendradvs** [comment]
Sorry it doesn't seem to work, just tried and where do we define the percent value in our code.

**Comment by bootsoon** [comment]
`formatTitle` is a callback function. ng-circle-progress calls it when your progress changes. 

```HTML
<circle-progress ...
    [percent]="otherPercentVariable" 
    [titleFormat]="formatTitle"></circle-progress>
```

```Typescript
formatTitle = (percent: number)  => {
  return [ "", percent + "%"]
}
```

You change the variable `otherPercentVariable` or receive a value from a backend service and assign it to `otherPercentVariable`. The `formatTitle` function will be called and the title will change.

**Comment by lokendradvs** [comment]
Great thanks but it is overlapping 
![image](https://user-images.githubusercontent.com/97017375/157046418-03c43635-6ca7-4c3d-9d24-c39eab5fb07c.png)

**Comment by bootsoon** [comment]
Hide the unit (`showUnits=false`) and handle  `subtitleFormat` function as the same as `titleFormat`.

**Comment by lokendradvs** [comment]
Great thanks,  Now it looks fine to me
