### ISSUE TITLE
I am developing an mobile application using ionic and angular4, i want the output based on swipe a percent in one progress circle, i.e.,  1 = happy , ...,5 = unhappy. Can anyone help me to solve.

### ISSUE THREAD

**Issue by HamseniRaj** [bootsoon/ng-circle-progress#18]
![image](https://user-images.githubusercontent.com/28753730/35086596-0fb6ff38-fc53-11e7-83f7-33651e53b4fd.png)

how can i get this type of circle progress. i am using correct one for this. Any suggestions please

**Comment by bootsoon** [comment]
@HamseniRaj  Make several svg paths with different data-value along the circle, then bind them to an event in which, and  output the data-value when a path is clicked.

**Comment by HamseniRaj** [comment]
Thanks for your reply,I am very new to this, can you please give an example (sample code)to this.
