### ISSUE TITLE
Can anyone suggest how to make this circle responsive?

### ISSUE THREAD

**Issue by sivakrishna01** [bootsoon/ng-circle-progress#19]

**Comment by jmeade11** [comment]
An SVG graphic can scale to the size of its parent when the `viewBox` property is used.  To make sure the SVG scales within the viewBox best, you can add the `preserveAspectRatio` property.

I would do this by editing the [circle-progrss.component.ts](https://github.com/bootsoon/ng-circle-progress/blob/master/src/circle-progress.component.ts#L91) file on line 91 by adding the following **inside the `<svg>` tag**:

    [attr.viewBox]="0 0 svg.width svg.height" [attr.preserveAspectRatio]="xMidYMid meet"

With the template component modified, use CSS to apply width and height values to the svg.  For example, you could add the following to your CSS file to cause any svg element to scale to 100% the height and width of their container values. 

    svg {
      width: 100%;
      height: 100%;
    }

**Remember that the containing element must have a fixed height** (use vh, vw, vmax, vmin, or fixed values like px), or an inherited fixed height.  Without a fixed height, the container will collapse and the SVG will only be able to scale in width (the preserveAspectRatio value will prevent it from getting out of proportion at least).

**Comment by doraymifasola** [comment]
@bootsoon. Thanks mate.
