### ISSUE TITLE
Add possibility to pass additional parameters

### ISSUE THREAD

**Issue by oleksandrh** [bootsoon/ng-circle-progress#2]
Thanks for this component. It's very useful for me.
In need something like this.
![image](https://user-images.githubusercontent.com/22424313/32327560-9d895c76-bfdf-11e7-823d-c23c6e2a3688.png)
If you know how to make this using existing functionality please help me.
If no, I suggest to add innerRadius, outerRadius,

**Comment by bootsoon** [comment]
@oleksandrh  No, I cannot make that using existing parameters, but I think I can fix it within a few days. Your suggestion is of great use, thanks.

**Comment by bootsoon** [comment]
@oleksandrh Please try 0.9.7, I have fix it.

![counter-clockwise](https://user-images.githubusercontent.com/20899374/32687907-b2e354c2-c701-11e7-9819-c2b9bd3e7e1b.png)

```
{
    percent: 75,
    radius: 60,
    outerStrokeWidth: 10,
    innerStrokeWidth: 10,
    space: -10,
    outerStrokeColor: "#4882c2",
    innerStrokeColor: "#e7e8ea",
    showBackground: false,
    title: 'UI',
    animateTitle: false,
    showUnits: false,
    clockwise: false,
    subtitleFormat: (percent: number): string => {
      return `${percent}%`;
    }
  }
```
