### ISSUE TITLE
Is there going to be support for angular 5?

### ISSUE THREAD

**Issue by gitLee47** [bootsoon/ng-circle-progress#22]
![image](https://user-images.githubusercontent.com/9353130/38112127-f193900e-336e-11e8-8761-3ef015abdf7f.png)

I am getting the following warning for a new angular 5 project.

**Comment by bootsoon** [comment]
@tahminabs23 at the end of this month.

**Comment by bootsoon** [comment]
@gitLee47 @garethharding @tahminabs23 Please update to ng-circle-progress@1.0.0 which removes the warning from Angular 5 projects.
