### ISSUE TITLE
Ionic -inner stroke circle not showing up in android device but showing up in browser 

### ISSUE THREAD

**Issue by nnonimus** [bootsoon/ng-circle-progress#24]
`    <circle-progress name="progress-bar" item-left [percent]="23" [radius]="100" [outerStrokeWidth]="16" [innerStrokeWidth]="8" [outerStrokeColor]="'#0094db '" [innerStrokeColor]="'#0094db91 '" [animation]="true" [animationDuration]="300"
                    [toFixed]="2"></circle-progress>`

**Comment by bootsoon** [comment]
@nnonimus Could you post detail here?
