### ISSUE TITLE
Max percent lower than 100 issue

### ISSUE THREAD

**Issue by Nlghtmare** [bootsoon/ng-circle-progress#25]
I read previous issues about max percent and as far as I can see circle is always acting like max is 100 if I set value lower than 100. 
E.g. I want my circle always be completed (percent and max percent same values), but it works only if percent and maxPercent are >=100. 
For lower values I can see + by the title value, but it is not ok if my circle is partially completed.

**Comment by bootsoon** [comment]
@Nlghtmare `maxPercentage` isn't a total and `percent` always represents the actual progress. E.g. If `percent` is set to 50, the circle is always half full no matter how many  `maxPercent` is. 
`maxPercent` cause the default title show a "+" at the right side of the number if it's less than the  `percent`.  Always set `percent` to 100 if you want your circle always be completed. Use `titleFormat` callback to show something else as title.

**Comment by Nlghtmare** [comment]
That will work, thank you :)
