### ISSUE TITLE
How can I change the text position inside of circle

### ISSUE THREAD

**Issue by Ethan0721** [bootsoon/ng-circle-progress#26]
So currently I make the innerStroke be 0 then the 85% will show up in the top inside of the outerStroke So I want make 85% be in the center in the outerStroke. Is there any property can control of that?

**Comment by Ethan0721** [comment]
Never mind I got it. through setting backgroundPadding

**Comment by Ethan0721** [comment]
got it thanks!

**Comment by wrzr123** [comment]
Is there some possibility to shift the position of the text? In my case I have title and subtitle. Title is centered, subtitle is below. I would like to have them centered together, or in general manually influence the text position.
Is this somehow possible?
