### ISSUE TITLE
Not showing first time ?

### ISSUE THREAD

**Issue by goel-sunny** [bootsoon/ng-circle-progress#28]
Hi ,

I am using this component in my project , but what i found is that it is not showing at first time inside the main component but shown second time (mean at the time of another event fire in any where in the application ) . can you tell me the what can be the root cause for that .

**Comment by bootsoon** [comment]
It might have something to do with Angular's component change detection strategies.

Didn't have the same issue. Would you post your code here?

**Comment by bootsoon** [comment]
The outer circle progress shows up without animation if `animation` is `false`.

https://github.com/bootsoon/ng-circle-progress/blob/c40195f9043e34497930e68abe9ddee723fadeed/src/circle-progress.component.ts#L241

`renderOnClick` tells the outer circle to animate when svg is clicked even if `animation` is `false`.

https://github.com/bootsoon/ng-circle-progress/blob/c40195f9043e34497930e68abe9ddee723fadeed/src/circle-progress.component.ts#L474

What do you exactly mean when you say

> it is not showing at first time inside the main component
