### ISSUE TITLE
Not able to generate small circle

### ISSUE THREAD

**Issue by omprakashpatel** [bootsoon/ng-circle-progress#3]
Hi, I tried ng-circle-progress it works smoothly for me.

But I have one issue with this, I want to generate small size circles only (ex: radius=10px). but when I pass radius=10 , circle size is still around 100x100 (radius around 50px)

```
<circle-progress
[percent]="85" [radius]="10"
[outerStrokeWidth]="4"
[innerStrokeWidth]="2"
[space]="-4"
outerStrokeColor="#82c42d"
innerStrokeColor="#d8e3e6"
[showSubtitle]="false"
[showUnits]="false"></circle-progress>
```

I looked into **circle-progress.component.ts** code then I found one condition there It sets radius=50 if it is less then 50. Is there issue if we allow to generate small circles..
https://github.com/bootsoon/ng-circle-progress/blob/master/src/circle-progress.component.ts#L219

**Comment by bootsoon** [comment]
@omprakashpatel If we allow to generate too small circles, there leaves no place for the title and subtitle. I can fix it if you really need small circles.

**Comment by stas-kh** [comment]
Yes, that's nice to have!

**Comment by bootsoon** [comment]
@stas-kh I'll fix it this week.

**Comment by Alexmartinez3** [comment]
You can apply a scale transformation to container of circle progress. I try this and work fine for me. 

```
.container{
	 transform: scale(0.8);
}
```

Hope it helps you!!

**Comment by omprakashpatel** [comment]
@bootsoon if possible would be very helpful.

as of now i solved my problem using https://github.com/lugolabs/circles library. some times it has invocation issue with angular app.

**Comment by omprakashpatel** [comment]
@bootsoon if possible would be very helpful.

as of now i solved my problem using https://github.com/lugolabs/circles library. some times it has invocation issue with angular app.

**Comment by bootsoon** [comment]
@omprakashpatel Please update to 0.9.8 which allows small radius.
