### ISSUE TITLE
bg-circle-progress doesn't support angular v6

### ISSUE THREAD

**Issue by charedim** [bootsoon/ng-circle-progress#30]
I upgraded angular to v6, and rxjs to @6.1.0
I get an error 
``` R in ./node_modules/ng-circle-progress/index.js
Module not found: Error: Can't resolve 'rxjs/Rx' in /home//a5/node_modules/ng-circle-progress '```

**Comment by alexjx** [comment]
Seems caused by the breaking changes of RxJS v6.
I workaround this by using the rxjs-compat.

Reference: [rxjs migration guide](https://github.com/ReactiveX/rxjs/blob/master/MIGRATION.md#backwards-compatibility)
