### ISSUE TITLE
opacity is inherited from parent div

### ISSUE THREAD

**Issue by shariqshahzad** [bootsoon/ng-circle-progress#41]
i wanted to make the whole screen transparent except the progress loader but it didnt work out, if im missing something please let me know

**Comment by bootsoon** [comment]
`backgroundColor='white'`
`showBackground=true`

**Comment by shariqshahzad** [comment]
![image](https://user-images.githubusercontent.com/29894072/44133434-31c97b30-a079-11e8-9db7-76f5a967a2ba.png)
still the same

**Comment by shariqshahzad** [comment]
NgCircleProgressModule.forRoot
            ({
            "backgroundPadding": 10,
            "radius": 60,
            "maxPercent": 100,
            "outerStrokeWidth": 10,
            "outerStrokeColor": "#61A9DC",
            "innerStrokeWidth": 0,
            "subtitleColor": "#444444",
            "showInnerStroke": false,
            "startFromZero": false,
            "backgroundColor": "white",
            "showBackground": true
            }),

**Comment by shariqshahzad** [comment]
app.module:
        NgCircleProgressModule.forRoot
            ({
            "backgroundPadding": 10,
            "radius": 60,
            "maxPercent": 100,
            "outerStrokeWidth": 10,
            "outerStrokeColor": "#61A9DC",
            "innerStrokeWidth": 0,
            "subtitleColor": "#444444",
            "showInnerStroke": false,
            "startFromZero": false,
            "backgroundColor": "white",
            "showBackground": true
            }),

component.html:
    <div class="fadeScreen" *ngIf="true">
        <div class="loaderCenter">
            <circle-progress
                             [percent]="completePercentage"
                             maxPercent=100>
            </circle-progress>
        </div>
    </div>

css classes:
.loaderCenter {
    top: 50%;
    left: 50%;
    width: 10em;
    height: 10em;
    margin-top: -5em;
    margin-left: -5em;
    position: relative;
}
.fadeScreen {
    position: fixed;
    top: 0;
    height: 100%;
    width: 100%;
    left: 0;
    background: black;
    opacity: 0.5;
    z-index: 2;
}

this is how it is configured

**Comment by bootsoon** [comment]
@shariqshahzad 

```
<style>
  .loaderCenter {
    top: 50%;
    left: 50%;
    width: 10em;
    height: 10em;
    margin-top: -5em;
    margin-left: -5em;
    position: relative;
}
.fadeScreen {
    position: fixed;
    top: 0;
    height: 100%;
    width: 100%;
    left: 0;
    background: black;
    opacity: 0.8;
    z-index: 2;
}
</style>
<div class="fadeScreen" *ngIf="true">
  <div class="loaderCenter">
      <circle-progress [percent]=50 [showBackground]='true' [backgroundColor]="'white'"></circle-progress>
  </div>
</div>
```


![image](https://user-images.githubusercontent.com/20899374/44266811-882bd680-a25e-11e8-88be-55a8f7ce87c0.png)

**Comment by shariqshahzad** [comment]
Thanks for  the help but it still looks blur , actually I was making a blunder the loader shouldn't be under that fade screen class . instead it should be outside it like this
`    <div *ngIf="isLoading"  class="fadeScreen"></div>
    <div *ngIf="isLoading" class="loaderCenter">
        <circle-progress
                            [percent]="completePercentage"
                            maxPercent=100>
        </circle-progress>
    </div>`
and its z-index should be higher than the fade screen div
![image](https://user-images.githubusercontent.com/29894072/44267236-ecdb3700-a246-11e8-912a-f3cd8c4367f7.png)

now it is supposed to be like this (left) as it is not blur like the one on right.

**Comment by bootsoon** [comment]
```
<style>
#d1{width:200px;height:200px;background-color:green;opacity:0.5;}
#d2{width:100px;height:100px;background-color:red;opacity:1;}
</style>
<div id="d1">
  <div id="d2"/>
</div>
```

You'll get the left one rather the right one.

![image](https://user-images.githubusercontent.com/20899374/44295090-87358c00-a2d4-11e8-941f-5d56cdd2f51c.png)
