### ISSUE TITLE
how to use ng-circle-progress src code in an angular project?

### ISSUE THREAD

**Issue by faribajpr** [bootsoon/ng-circle-progress#42]
I'm using angular 6 and I want to use ng-circle-progress. I implemented the circles but I want to change something that I think I should do it from the src code. there is a `units` and `title `options in the circles and I want them to get closer to each other. How can I do it?

**app.module.ts**

```
import {
  NgCircleProgressModule
} from 'ng-circle-progress';

imports: [
  CommonModule,
  RouterModule.forChild(HomeRoutingModule),
  NgCircleProgressModule.forRoot({
    "units": "Liter",
    "outerStrokeLinecap": "butt"
  })
]
```

**home.component.html**
`<circle-progress
    [percent]="65"
    [radius]="100"
    [outerStrokeWidth]="8"
    [innerStrokeWidth]="2"
    [outerStrokeColor]=tank.outerColor
    [innerStrokeColor]="'#e2e2e2'"
    [animation]="true"
    [animationDuration]="300"
    [space]="5"
    [showSubtitle]= "false"
    [showUnits]= "true"
    [unitsFontSize]= "15"
    [titleFontSize]= "45"
    [clockwise]= "false">
</circle-progress>`

and this is the image of output. how can I control the space between 65 and liter?

![untitled55](https://user-images.githubusercontent.com/33823943/44640099-d9f9fc80-a9d4-11e8-8550-6521d26b6e1b.png)

**Comment by bootsoon** [comment]
Copy `circle-progress.component.ts` and `ng-circle-progress.module.ts` into your source folder.

![image](https://user-images.githubusercontent.com/20899374/44786798-d67a9700-abc7-11e8-9511-d175183d07db.png)

1. Change `app.module.ts `:

`import { NgCircleProgressModule } from 'ng-circle-progress';`
-->
`import { NgCircleProgressModule } from './ng-circle-progress.module';`

2. Change `app.component.ts `:

`import { CircleProgressComponent, CircleProgressOptions } from 'ng-circle-progress';`
-->
`import { CircleProgressComponent, CircleProgressOptions } from './circle-progress.component';`

**Comment by faribajpr** [comment]
@bootsoon i did it but i get the below error: 
` StaticInjectorError(Platform: core)[CircleProgressComponent -> CircleProgressOptions]: 
    NullInjectorError: No provider for CircleProgressOptions!`

i have a hom.module and inside home folder i have circle component and module. and imported circle module in home module and after that in home.html i used : 
`<circle-progress [percent]=tank.percent [radius]="100" [outerStrokeWidth]="12" [innerStrokeWidth]="2"
            [outerStrokeColor]=tank.outerColor [innerStrokeColor]="'#e2e2e2'" [animation]="true" [animationDuration]="300"
            [space]="5" [showSubtitle]="false" [showUnits]="true" [unitsFontSize]="15" [titleFontSize]="45" [clockwise]="false"
            [responsive]="false" [class]="'center-block cursor-pointer'"></circle-progress>`

but i get error!!

**Comment by faribajpr** [comment]
@bootsoon  I solved it, I should put  `CircleProgressOptions `in providers list in app.module! thanks for your helps!

**Comment by bootsoon** [comment]
@faribajpr You are welcome.

**Comment by dhair-seva** [comment]
Hope this helps someone in the future.

@bootsoon with this type of library, manually importing a provider isn't best since the library should expose it. After looking into the module, it looks like CircleProgressOptions is only exposed if you add the forRoot() in your module.

See code below:
```
  static forRoot(options: CircleProgressOptionsInterface = {}): ModuleWithProviders {
    return {
      ngModule: NgCircleProgressModule,
      providers: [
        {provide: CircleProgressOptions, useValue: options}
      ]
    };
  }
```
After doing this, it fixed it on my end.

So in my module, I had this in my list of imports:
```
NgCircleProgressModule.forRoot(),
```
