### ISSUE TITLE
how can i draw a circle progress with two parameters?

### ISSUE THREAD

**Issue by faribajpr** [bootsoon/ng-circle-progress#43]
I'm using angular 5 and I want to draw a circle-progress chart that shows two item changes in one chart! how can I implement it? I need something like this picture:

![untitled666](https://user-images.githubusercontent.com/33823943/44982804-51f39400-af8c-11e8-904a-a98d62a9626e.png)

as you see, the yellow part and the blue part are totally separated and show different numbers but they are in a unit chart.

**Comment by bootsoon** [comment]
ng-circle-progress can't draw two circle-progress at the same time.

**Comment by faribajpr** [comment]
@bootsoon do you know any other way to do it? I searched alot but I didn't find anything

**Comment by bootsoon** [comment]
@faribajpr You can build a two-circle-progress based on ng-circle-progress.  :)

https://github.com/bootsoon/ng-circle-progress/blob/5a01e1144a340eb7b8e9c55b5d3f54c67a89bacf/src/circle-progress.component.ts#L111

Add another path into template to show the second progress bar.

https://github.com/bootsoon/ng-circle-progress/blob/5a01e1144a340eb7b8e9c55b5d3f54c67a89bacf/src/circle-progress.component.ts#L350

Add another path into ts to calculate the second path.
