### ISSUE TITLE
how to add image inside progress circle ?

### ISSUE THREAD

**Issue by Nileshdcool** [bootsoon/ng-circle-progress#44]
is it possible to add image inside the progress ??
as we see already text and some content already in their..so is there way to add image inside it ??

**Comment by bootsoon** [comment]
ref: https://github.com/bootsoon/ng-circle-progress/pull/6

**Comment by bootsoon** [comment]
@Nileshdcool  Please update to ng-circle-progress@1.3.0

```
  "imageSrc": "/assets/images/music.svg",
  "imageHeight": 105,
  "imageWidth": 105,
  "showImage": true,
```
