### ISSUE TITLE
How to place Image inside a progress bar

### ISSUE THREAD

**Issue by aaithu-pk** [bootsoon/ng-circle-progress#46]
I want image inside a progress bar is there a way?

**Comment by aaithu-pk** [comment]
yes I want image int the center of the circle like uploaded image
![image](https://user-images.githubusercontent.com/38241720/46270826-23ef7880-c567-11e8-8f6a-63d2051bbca3.png)

**Comment by aaithu-pk** [comment]
any update on this

**Comment by bootsoon** [comment]
@aaithu-pk Please update to ng-circle-progress@1.3.0

```
  "imageSrc": "/assets/images/music.svg",
  "imageHeight": 105,
  "imageWidth": 105,
  "showImage": true,
```

**Comment by fayaz07** [comment]
I have updated to version 1.3.0 even it doesn't work
