### ISSUE TITLE
Padding and font weight for title and subtitle

### ISSUE THREAD

**Issue by spalmaro** [bootsoon/ng-circle-progress#49]
Hello, I was wondering if there was a way to access the padding of the title as it seems to be closer to the top than in the middle. And also if we could affect the font-weight? 

![image](https://user-images.githubusercontent.com/23173270/47316525-a095e400-d647-11e8-8e9c-7623154c2ab2.png)

**Comment by bootsoon** [comment]
The title is in the center of the circle if you hide the subtitle and the unit.

There is no way to control the padding of title.

**Comment by khaled9544** [comment]
It possible to change the title location? For Example: Inside the line.

**Comment by bootsoon** [comment]
@khaled9544 What does it look like?

**Comment by spalmaro** [comment]
Hi @bootsoon, what about the font-weight? Is that a possibility?

**Comment by bootsoon** [comment]
@spalmaro font-weight is possible.

**Comment by spalmaro** [comment]
@bootsoon How so? I cannot find documentation on it

**Comment by bootsoon** [comment]
I'll add font-weight in next release.

**Comment by bootsoon** [comment]
@spalmaro 1.4.0 is released. `titleFontWeight` `subtitleFontWeight` `unitsFontWeight` can now be set.
