### ISSUE TITLE
caught Error: Template parse errors: on  'circle-progress'  other then app.component.ts

### ISSUE THREAD

**Issue by gurudath** [bootsoon/ng-circle-progress#5]
Hi Bootsoon,

**I am getting the below error when trying other then app.component.ts,**

caught Error: Template parse errors:
Can't bind to 'percent' since it isn't a known property of 'circle-progress'.
1. If 'circle-progress' is an Angular component and it has 'percent' input, then verify that it is part of this module.
2. If 'circle-progress' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
          <span *ngIf="field['overview']">
            <div>
            <circle-progress [ERROR ->][percent]="85" [radius]="100" ></circle-progress>
            </div>
          </span>
"): ng:///AppRouteModule/PluginmediaComponent.html@11:29
Can't bind to 'radius' since it isn't a known property of 'circle-progress'.
1. If 'circle-progress' is an Angular component and it has 'radius' input, then verify that it is part of this module.
2. If 'circle-progress' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("     <span *ngIf="field['overview']">
            <div>
            <circle-progress [percent]="85" [ERROR ->][radius]="100" ></circle-progress>
            </div>
          </span>
"): ng:///AppRouteModule/PluginmediaComponent.html@11:44
'circle-progress' is not a known element:'

**I have added the 
app.module.ts**

@NgModule({
  imports: [
    BrowserModule,
    FormsModule,
    HttpModule,
    TranslateModule.forRoot({
      loader: {
        provide: TranslateLoader,
        useFactory: HttpLoaderFactory,
        deps: [Http]
      }
    }),
    NgCircleProgressModule.forRoot({
      radius: 100,
      outerStrokeWidth: 16,
      innerStrokeWidth: 8,
      outerStrokeColor: '#78C000',
      innerStrokeColor: '#C7E596',
      animationDuration: 300,
    }),
    BsDropdownModule.forRoot(),
    ProgressbarModule.forRoot(),
    AppRouteModule
  ],

**some.component.ts**
<circle-progress [percent]="85" [radius]="100" ></circle-progress>

**and installed using** 
npm install ng-circle-progress --save

i am using angular 4 application. 
"angular/common": "~4.4.6",
    "angular/compiler": "~4.4.6",
    "angular/core": "~4.4.6",
    "angular/forms": "~4.4.6",

Can you please help me to over come this issue or need to do some setting.

**Comment by bootsoon** [comment]
@gurudath Have you fixed it?

**Comment by gurudath** [comment]
Yes, it was in my application I need to declare in other abstracted module
rather than in app module

**Comment by wilmanh** [comment]
hi, can you be more specific about how you fixed it @gurudath

**Comment by algorys** [comment]
Facing to the same issue @wilmanh , in fact you have to import module inside the corresponding `page.module.ts` file to make it works. It is therefore not necessarily in the file `app.module.ts` that it must be imported.
