### ISSUE TITLE
Remove the outer stroke when the bar is at 0%

### ISSUE THREAD

**Issue by thoth3x** [bootsoon/ng-circle-progress#52]
Hello!

Is it possible to remove the outer stroke when the bar is at 0%?

<img width="231" alt="screenshot 2018-11-06 at 17 52 27" src="https://user-images.githubusercontent.com/16525987/48076067-250e6800-e1ed-11e8-9e7d-222a3479c433.png">

Great plugin btw!

**Comment by thoth3x** [comment]
> Is `showZeroOuterStroke`(default=true) a good idea?

That would be great!

**Comment by chandan-cordova** [comment]
::ng-deep {
  circle-progress[ng-reflect-percent="0"] path {
    stroke: transparent;
  }
}

**Comment by veer3383** [comment]
@chandan-cordova  Unfortunately, this solution does not works in production for me.

I achieved this by applying class dynamically.

**CSS**
::ng-deep .circle-stroke path {
	stroke: transparent;
}

**HTML**
<circle-progress [ngClass]="{'circle-stroke': item.progress === 0 || item.progress == undefined}" [percent]="item.progress * 100"></circle-progress>

**Comment by chandan-cordova** [comment]
Yeah aot build removes all ng-reflect-* things. A lesson for me :)

**Comment by bootsoon** [comment]
@thoth3x 1.4.0 is released. `showZeroOuterStroke` can be set to false to hide the bar when percent is 0.
