### ISSUE TITLE
Color Gradient

### ISSUE THREAD

**Issue by rshaurya1** [bootsoon/ng-circle-progress#57]
Is it possible to add a color gradient to the progress bar?
Thanks

**Comment by malayvc** [comment]
@bootsoon  I really appreciate your work and if you develop this functionality it would be awesome for all developer, Thanks in advance.

**Comment by bootsoon** [comment]
@rshaurya1 @malayvc 1.4.0 is released. 

Set `backgroundGradient=true` to make the background gradient.

Use `backgroundColor` and `backgroundGradientStopColor` to control the color.


Set `outerStrokeGradient=true` to make the outer circle(progress bar) gradient.

Use `outerStrokeColor` and `outerStrokeGradientStopColor` to control the color.



![image](https://user-images.githubusercontent.com/20899374/51822577-c3efbf80-2317-11e9-920c-5d93f3df25a3.png)

**Comment by Ovsdrak** [comment]
Can you provide a  `outerStrokeGradientDirection` property in order to have a vertical gradient, or a custom angle. I need to add `x2="0%" y2="100%"` attributes to `linearGradient` tag to solve my problem.

**Comment by bootsoon** [comment]
@Ovsdrak How does it look like?

**Comment by Ovsdrak** [comment]
@bootsoon it should looks like this.

![Captura de Pantalla 2020-03-12 a la(s) 10 07 24 a m](https://user-images.githubusercontent.com/20526969/76541552-677f2f00-6449-11ea-91b8-566f1e4b533b.png)

**Comment by kaipk** [comment]
> Can you provide a `outerStrokeGradientDirection` property in order to have a vertical gradient, or a custom angle. I need to add `x2="0%" y2="100%"` attributes to `linearGradient` tag to solve my problem.

hi, i also need this option, how do you solve this?
