### ISSUE TITLE
Not workin on Safari

### ISSUE THREAD

**Issue by matias3981** [bootsoon/ng-circle-progress#58]
I just figure out that it´s not working on safari for Mac. Im using Angular 6 and when i open in a Mac my web app in chrome it works but when i use it in safari and i see the circle-progress, the tab stop working.

**Comment by AcarMeel** [comment]
I have the same problem. Angular 6 and safari is not rendering the circle, is only displaying the title. The https://bootsoon.github.io/ng-circle-progress/  renders correctly in safari. But my app doesn't. I noticed I have a bunch of errors in the console (safari only) related to jquery.min. Don't know if it has to do with ng-circle cause in other browsers I don't have these issues or console errors.
I have done the implementation exactly the same as the documentation. I don't what's going on. Help!!!!

**Comment by lampham2505** [comment]
![Screenshot at Feb 28 14-42-14](https://user-images.githubusercontent.com/21020492/75520643-97393a80-5a38-11ea-9261-5e4040784fa9.png)

Here is my html code
<circle-progress 
        class="circle-progress"
        [percent]="percent"
        [radius]="120"
        [outerStrokeWidth]=20
        [innerStrokeWidth]=10
        [outerStrokeGradient]=true
        [outerStrokeColor]="'#5ED9F3'"
        [outerStrokeGradientStopColor]="'#2346DC'"
        [outerStrokeLinecap]=''
        [innerStrokeColor]="'#E3E3E3'"
        [showInnerStroke]=true
        [space]=-15
      > 

I see that the property "d" of "path" not showing in inspect mode.
Can anyone improve it?

**Comment by rohitsingh98191** [comment]
I also faced the same issue but putting outerStrokeGradient false resolved my issue on safari
