### ISSUE TITLE
'circle-progress' is not a know element

### ISSUE THREAD

**Issue by eBitzu** [bootsoon/ng-circle-progress#59]
'circle-progress' is not a known element:
1. If 'circle-progress' is an Angular component, then verify that it is part of this module.
2. If 'circle-progress' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.

Running on angular 6.1.0;
<circle-progress></circle-progress>

    NgCircleProgressModule.forRoot({
      backgroundOpacity: 0.9,
      radius: 66,
      space: 0,
      toFixed: 0,
      maxPercent: 100,
      outerStrokeWidth: 4,
      innerStrokeColor: '#c0c0c0',
      innerStrokeWidth: 5,
      subtitleFontSize: '15',
      showUnits: false,
      clockwise: false,
    }),

**Comment by SandyVeliz** [comment]
If you have more than one module use ir in the module of the component where you ll use it.

**Comment by rabinrai44** [comment]
I guess it is the same issue that I faced, you could try calling into `app-routing.module.ts`
