### ISSUE TITLE
Error: <circle> attribute r: A negative value is not valid.

### ISSUE THREAD

**Issue by albertoscandolara** [bootsoon/ng-circle-progress#62]
Good morning, i'm trying to use your circle progress to obtain something like (similar to a cake diagram):
![finalresult](https://user-images.githubusercontent.com/47004991/51693740-d1e3ce80-1fff-11e9-8494-057395c92870.PNG)

the parameters are set as folllow:
`<circle-progress
                      [radius]="4"
                      [percent]="setPercentage()"
                      [animation]="false"
                      [outerStrokeWidth]="8"
                      [backgroundPadding]="0"
                      [outerStrokeColor]="'#E29717'"
                      [backgroundColor]="'#E3E7EC'"
                      [showTitle]="false"
                      [showSubtitle]="false"
                      [showUnits]="false"
                      [showBackground]="true"
                      [outerStrokeLinecap]="'butt'"
                      [renderOnClick]="false"
                    >`

but i get the following error:
![error](https://user-images.githubusercontent.com/47004991/51693959-2b4bfd80-2000-11e9-876f-f1edb418d0fa.PNG)

Could you please explain what I am missing and (eventually) a tip on how to solve and get the desired result? important: i can't increase dimensions. 
Thanks in advance, this module is really great!

**Comment by bootsoon** [comment]
@albertoscandolara You can set showInnerStroke="false"

An inner circle shows by default but "-6" is invalid for a inner <circle.
