### ISSUE TITLE
progress no shown on mobile

### ISSUE THREAD

**Issue by HansKrywaa** [bootsoon/ng-circle-progress#64]
Hey, I'm using Ionic and the ng-circle-progress.
On my Testdevice (Android 5.1) the progress is not shown. I only see the blank circle.

Any Ideas why?

**Comment by nivel9** [comment]
I have the same issue but in Safari and IOS with Ionic 4. Works perfectly on Android and Firefox and Chrome. I am using a Mac.

Please help.
