### ISSUE TITLE
How to create a box-shadow or drop-shadow on svg circle stroke or on path?

### ISSUE THREAD

**Issue by rabinrai44** [bootsoon/ng-circle-progress#67]
I'd like to have a shadow on the progress bar. I'm trying to get the same as below in image progress bar an example: 
![image](https://user-images.githubusercontent.com/18373809/53210961-9e4f9080-360d-11e9-9aa1-84afd8d2ec99.png)
**It is possible to create a shadow/glow around the circle?** 

Thanks

**Comment by bootsoon** [comment]
No, it's impossible now.

**Comment by rabinrai44** [comment]
Thanks, I wish to have that feature in the future!

**Comment by anton-maslakov** [comment]
If it helps someone in future:

circle-progress svg {
  filter: drop-shadow(0px 18px 55px rgb(108 99 255 / 99%));
} - will do the trick

![image](https://user-images.githubusercontent.com/38735817/180215702-a4e47fcd-b22f-4fa7-9719-6682c421a4a9.png)
