### ISSUE TITLE
On my local it's but on production still showing old progress bar

### ISSUE THREAD

**Issue by Praveen111** [bootsoon/ng-circle-progress#68]
This is the code I'm using in my module

   NgCircleProgressModule.forRoot({
      "radius": 23,
      "space": 1,
      "unitsFontWeight": "600",
      "outerStrokeWidth": 5,
      "outerStrokeLinecap": "butt",
      "innerStrokeWidth": 0,
      "titleFontSize": "10",
      "titleFontWeight": "600",
      "showSubtitle": false,
      "showBackground": false,
      "showInnerStroke": false,
      "animationDuration": 10000,
        "outerStrokeColor": "#28e1d8",
      "outerStrokeGradientStopColor": "#70e284",
      renderOnClick: false
    })

but it's working only in my local,when others are running it, it's taking old values. cleared cache but still in production showing old progress bar. Not sure why ? should I npm uninstall and redo ? Any suggestions ?  I'm using "ng-circle-progress": "^1.4.0" version
 Angular version 6

**Comment by bootsoon** [comment]
Could you post your code?
