### ISSUE TITLE
Not working in safari

### ISSUE THREAD

**Issue by AcarMeel** [bootsoon/ng-circle-progress#69]
I have the same problem. Angular 6 and safari is not rendering the circle, is only displaying the title. The https://bootsoon.github.io/ng-circle-progress/ renders correctly in safari. But my app doesn't. I noticed I have a bunch of errors in the console (safari only) related to jquery.min. Don't know if it has to do with ng-circle cause in other browsers I don't have these issues or console errors.
I have done the implementation exactly the same as the documentation. I don't what's going on. My circle is using linear gradients. Don't know if that's the issue in safari. Help!!!!

**Comment by bootsoon** [comment]
Could you post your code here?
