### ISSUE TITLE
[Feature] Indeterminate state.

### ISSUE THREAD

**Issue by Domvel** [bootsoon/ng-circle-progress#71]
# Feature Request

Indeterminate state. Display a wait animation. Inspired by the material progress bar. See gif animation below.
![export](https://user-images.githubusercontent.com/35452565/55013806-2d274280-4fea-11e9-9cab-841e3eecf5e6.gif)

This could be an additional optional boolean parameter for the component.

**Comment by bootsoon** [comment]
I think it will make the progress bar confusing. Isn't it?

**Comment by Domvel** [comment]
@bootsoon Hehe 😄 ... No, I don't think so. It's just an indicator for "Keep waiting, I'm working." This is a state of no progress in percent. This is a well known behavior / animation.
You can use this as placeholder and for general user actions. A state of preparing.

[See here](https://material.io/design/components/progress-indicators.html#circular-progress-indicators) and [here](https://material.angular.io/components/progress-spinner/overview)

**Comment by khalilou88** [comment]
I wanted to use this lib for this exactly case. hope it will be added.

**Comment by Domvel** [comment]
I use this [Progress Circle](https://www.npmjs.com/package/ui-progress-circle) because it supports that and is more responsive and flexible. ...
