### ISSUE TITLE
x and y on imageSrc

### ISSUE THREAD

**Issue by Nik1990** [bootsoon/ng-circle-progress#73]
Hi, when a imageSrc is used, in console i receive this error in console:

`
Error: <image> attribute x: Expected length, "NaN"
Error: <image> attribute y: Expected length, "NaN".
`

there is a way to set x and y of image inside circle?

Thanks?

**Comment by bootsoon** [comment]
There's no way to set x and y of the image inside the circle. It'll be always in the middle of the circle.

Why you want to set x and y of it?
