### ISSUE TITLE
Animate when 'visible'

### ISSUE THREAD

**Issue by hdimessi** [bootsoon/ng-circle-progress#75]
So I was thinking is it possible to only trigger the animation once the cirlce is visible,
For example imagine i have the circule in the bottom on a scroll, the user then won get the chance to see the animation, another reason is when trying to add multiple circles (for example over 40) some visible and some not (will be once the user scroll down) then this new feature I m proposing will help with performance as well

**Comment by bootsoon** [comment]
Great idea. I'll try.

**Comment by bootsoon** [comment]
@hdimessi Please update to 1.4.1 which introduces a new property `lazy=true`.

The circle pauses at the last position when it's out of viewport and becomes active again when visible, listening to events of scrolling and window resizing.


![nxqTJAvUdY](https://user-images.githubusercontent.com/20899374/58494075-da633600-81a6-11e9-9c4e-0dca51b3607f.gif)

**Comment by NikhilGangurde** [comment]
how to stop animation after the first load.

**Comment by bootsoon** [comment]
set animation to false
