### ISSUE TITLE
Doesn't work on safari or iPhone

### ISSUE THREAD

**Issue by developerwillz** [bootsoon/ng-circle-progress#79]
I'm following a tutorial on youtube and the code is in this repo: https://github.com/designcourse/ionic-4-crash-course-project-restrr

it works perfectly on chrome but circle-progress doesn't work on safari. when I deploy it to iPhone, it also doesn't work.

**Comment by bootsoon** [comment]
Too bad. I sold my Mac Air last year and I'm now using a ThinkPad. 

No safari. Can I install an iOS in Virtualbox?
