### ISSUE TITLE
template error

### ISSUE THREAD

**Issue by vladimircojuhari** [bootsoon/ng-circle-progress#8]
hello, im trying to use your plugin but i have a problem. after my imports it doesnt work in my ionic 2 app. 
1)app module: 
![image](https://user-images.githubusercontent.com/28889904/33484632-05ebbe4c-d658-11e7-8038-e90b53f35ca7.png)

2) home page for ex.
![image](https://user-images.githubusercontent.com/28889904/33484647-0fdc2b1c-d658-11e7-871c-7d1aa79e5947.png)

3)the error.
![image](https://user-images.githubusercontent.com/28889904/33484658-2104b2f6-d658-11e7-90e2-abe50e87886e.png)
pls help me) thx for attention

**Comment by vladimircojuhari** [comment]
resloved. colors should be in this format: [outerStrokeColor]="'#ccc'"

**Comment by bootsoon** [comment]
@vladimircojuhari 

You can bind just a fixed string to a property,

 `outerStrokeColor="#ccc"`

or use one-way binding with expression-syntax.

`[outerStrokeColor]="'#ccc'"`
