### ISSUE TITLE
Extra space at the end of title/subtitles

### ISSUE THREAD

**Issue by danieldanielecki** [bootsoon/ng-circle-progress#80]
There's an added extra space after title and subtitle elements, which makes it not centered. It also doesn't look good if you have number with its corresponding % next to each other making there an unnecessary space. From source code point of view it's all about the `<tspan>` element. The problem is highlighted by red colour, the same applies to the [demos](https://bootsoon.github.io/ng-circle-progress/) examples where there's a an empty space between % number and the symbol '%', plus it's not centered as well. You can easily see it based on the demos, which have title and subtitle that the title text is more on the left side, instead of centered.

![extra_space2](https://user-images.githubusercontent.com/12736263/58007234-24cf1d80-7aea-11e9-8a11-47e170b86f8c.PNG)
![extra_space](https://user-images.githubusercontent.com/12736263/58007237-2698e100-7aea-11e9-9197-e5237e01ba33.PNG)

**Comment by ruimartins21** [comment]
Same problem here.
Does someone know how to solve it?
Thank you

**Comment by bootsoon** [comment]
Failed to find an elegant way to remove trailing white spaces in Angular. 

`preserveWhitespaces` works for white spaces between tags but not those in a tag.

The only way to remove such white spaces is to remove all spaces from template in source code.

I'll remove the white spaces in the string in all tags if there's no other way to solve the issue.

Any help?

**Comment by danieldanielecki** [comment]
Line 439 starting from `template: "\n        <svg xmlns=\"http://www.w3.org/2000/svg\"` onwards in **index.js** is the part where I tried to remove all the spaces, but still couldn't get it working. Is there any other part of the code you're talking about with the white spaces?

**Comment by ruimartins21** [comment]
@bootsoon I can't get the result that I want. Could you fix it for us? Thanks in advance.

**Comment by bootsoon** [comment]
@ruimartins21 I'll release version 1.4.1 to fix #80 ASAP.

**Comment by bootsoon** [comment]
@danieldanielecki @ruimartins21 Please update to 1.4.1.

![no-more-extra-space](https://user-images.githubusercontent.com/20899374/58494466-bce29c00-81a7-11e9-9847-18cf57b97050.png)

**Comment by danieldanielecki** [comment]
Confirmed, working fine in the 1.4.1, thank you!

**Comment by ruimartins21** [comment]
@bootsoon I just updated to version 1.4.1. Seems that the spacing issue was fixed but now the circle didn't load to the supposed percentage and stays at 0%. I reverted and it worked fine.
There is any change that I need to make in the code after this update?
Sorry for the inconvenience and keep up the good work.
