### ISSUE TITLE
onclick event on a button stops the progress circle

### ISSUE THREAD

**Issue by MeriemBo** [bootsoon/ng-circle-progress#81]
Hello , can I use an external element of circle-progress to trigger events on the circle ? For example add a button and a click event to stop the progress circle ? Thanks

**Comment by bootsoon** [comment]
No Input event now.  Send a message to ng-circle-progress? Why and how ?

**Comment by MeriemBo** [comment]
I'm sorry but I don't understand your question .

**Comment by bootsoon** [comment]
What do you want to do with the progress circle?

**Comment by MeriemBo** [comment]
I want to be able to stop and restart the progress circle by clicking on a stop/start button and also store the percentage where it stops.

**Comment by bootsoon** [comment]
OK. I'll try.

**Comment by MeriemBo** [comment]
Okay , thank you

**Comment by tarun57** [comment]
Hello i'm using this progress bar but i am not able to stop progress bar on click.

**Comment by bootsoon** [comment]
@MeriemBo  

You can keep `percent` unchanged if you want to **pause** the circle progress. Isn't it simple?

Do you have a better way to pause it? Another property `paused` ?

**Comment by MeriemBo** [comment]
I couldn't find a way to pause the circle.
