### ISSUE TITLE
Error on Angular 7

### ISSUE THREAD

**Issue by tingspain** [bootsoon/ng-circle-progress#83]
Hello I am new with Angular and Ionic, I was trying to use ng-circle-prograss component, but it gives an error. I just used the very simple example, the one on the documentation but i always got the following error:

`
ERROR Error: "Uncaught (in promise): Error: Template parse errors:
Can't bind to 'percent' since it isn't a known property of 'circle-progress'.
1. If 'circle-progress' is an Angular component and it has 'percent' input, then verify that it is part of this module.
2. If 'circle-progress' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("

    <circle-progress
    [ERROR ->][percent]="85"
    [radius]="100">
    </circle-progress>
"): ng:///TodayPageModule/TodayPage.html@6:4
Can't bind to 'radius' since it isn't a known property of 'circle-progress'.
1. If 'circle-progress' is an Angular component and it has 'radius' input, then verify that it is part of this module.
2. If 'circle-progress' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
    <circle-progress
    [percent]="85"
    [ERROR ->][radius]="100">
    </circle-progress>

"): ng:///TodayPageModule/TodayPage.html@7:4
'circle-progress' is not a known element:
1. If 'circle-progress' is an Angular component, then verify that it is part of this module.
2. If 'circle-progress' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("

    [ERROR ->]<circle-progress
    [percent]="85"
    [radius]="100">
"): ng:///TodayPageModule/TodayPage.html@5:4
syntaxError@http://localhost:8100/vendor.js:8988:17
./node_modules/@angular/compiler/fesm5/compiler.js/TemplateParser.prototype.parse@http://localhost:8100/vendor.js:27163:19
./node_modules/@angular/compiler/fesm5/compiler.js/JitCompiler.prototype._parseTemplate@http://localhost:8100/vendor.js:32729:37
./node_modules/@angular/compiler/fesm5/compiler.js/JitCompiler.prototype._compileTemplate@http://localhost:8100/vendor.js:32716:23
./node_modules/@angular/compiler/fesm5/compiler.js/JitCompiler.prototype._compileComponents/<@http://localhost:8100/vendor.js:32659:62
./node_modules/@angular/compiler/fesm5/compiler.js/JitCompiler.prototype._compileComponents@http://localhost:8100/vendor.js:32659:19
./node_modules/@angular/compiler/fesm5/compiler.js/JitCompiler.prototype._compileModuleAndComponents/<@http://localhost:8100/vendor.js:32569:19
then@http://localhost:8100/vendor.js:8979:77
./node_modules/@angular/compiler/fesm5/compiler.js/JitCompiler.prototype._compileModuleAndComponents@http://localhost:8100/vendor.js:32568:26
./node_modules/@angular/compiler/fesm5/compiler.js/JitCompiler.prototype.compileModuleAsync@http://localhost:8100/vendor.js:32528:37
./node_modules/@angular/platform-browser-dynamic/fesm5/platform-browser-dynamic.js/CompilerImpl.prototype.compileModuleAsync@http://localhost:8100/vendor.js:65512:31
./node_modules/@angular/core/fesm5/core.js/SystemJsNgModuleLoader.prototype.loadAndCompile/<@http://localhost:8100/vendor.js:52405:60
./node_modules/zone.js/dist/zone.js/</ZoneDelegate.prototype.invoke@http://localhost:8100/polyfills.js:2753:26
onInvoke@http://localhost:8100/vendor.js:51342:33
./node_modules/zone.js/dist/zone.js/</ZoneDelegate.prototype.invoke@http://localhost:8100/polyfills.js:2752:52
./node_modules/zone.js/dist/zone.js/</Zone.prototype.run@http://localhost:8100/polyfills.js:2512:43
scheduleResolveOrReject/<@http://localhost:8100/polyfills.js:3251:34
./node_modules/zone.js/dist/zone.js/</ZoneDelegate.prototype.invokeTask@http://localhost:8100/polyfills.js:2785:31
onInvokeTask@http://localhost:8100/vendor.js:51333:33
./node_modules/zone.js/dist/zone.js/</ZoneDelegate.prototype.invokeTask@http://localhost:8100/polyfills.js:2784:60
./node_modules/zone.js/dist/zone.js/</Zone.prototype.runTask@http://localhost:8100/polyfills.js:2557:47
drainMicroTaskQueue@http://localhost:8100/polyfills.js:2963:35
"
    Angular 8
core.js:15724
`

**Comment by bootsoon** [comment]
```
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';

import { AppComponent } from './app.component';

// Import ng-circle-progress
import { NgCircleProgressModule } from 'ng-circle-progress';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,

    // Specify ng-circle-progress as an import
    NgCircleProgressModule.forRoot({
      // set defaults here
      radius: 100,
      outerStrokeWidth: 16,
      innerStrokeWidth: 8,
      outerStrokeColor: "#78C000",
      innerStrokeColor: "#C7E596",
      animationDuration: 300,
      ...
    })

  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

**Comment by tingspain** [comment]
Thanks!!
