### ISSUE TITLE
Not loading percent when page is loaded

### ISSUE THREAD

**Issue by Wen-bg** [bootsoon/ng-circle-progress#85]
When my page is loaded I have to click for it to load the percent and it gets stuck on some percents.

module:

` NgCircleProgressModule.forRoot({
      // set defaults here
      "radius": 60,
      "outerStrokeWidth": 10,
      "innerStrokeWidth": 5,
      "showBackground": false,
      "startFromZero": false
      
    })
 `

html 
`<circle-progress
  [percent]="100"
  [radius]="100"
  [outerStrokeColor]="'#78C000'"
  [innerStrokeColor]="'#C7E596'"
  [animation]="true"
  [animationDuration]="300"

></circle-progress>`

**Comment by bootsoon** [comment]
Do you have the same issue with this demo? 

https://bootsoon.github.io/ng-circle-progress/

**Comment by fatoum** [comment]
i used the same code but i have same problem , the progreess bar is not rendering when my page is loaded , i should clickek inside the progress bar to loaded , how can i displayed the percentage when my page is loaded ?

**Comment by Bilelkabtni** [comment]
i had the same issue :(

**Comment by iPazooki** [comment]
I have the same issue, by default progress bar will not process until you click!

**Comment by iPazooki** [comment]
> Do you have the same issue with this demo?
> 
> https://bootsoon.github.io/ng-circle-progress/

I don't have this issue with demo site, but it seems some option or property is missing in the documentation!

I mean there should be some property or option to render the circle as soon as it was soon.

**Comment by Bilelkabtni** [comment]
@iPazooki i even check the source code there is no option or event to trigger the render function there is only a Boolean renderOnclick and it just enable/disable the click event.

**Comment by iPazooki** [comment]
> @iPazooki i even check the source code there is no option or event to trigger the render function there is only a Boolean renderOnclick and it just enable/disable the click event.

Exactly, it seems something is missing ...
@bootsoon  We need some help here ;)

**Comment by iPazooki** [comment]
@Bilelkabtni  I found the solution, please set `lazy: false`

**Comment by fatoum** [comment]
@iPazooki  , it works for me , thank you :)

**Comment by bootsoon** [comment]
`lazy` is a feature introduced in 1.4.1. It's used to pause the circle when out of viewport. 

If everything is OK the circle progress bar should process whether or not `lazy` is true when `<svg>` tag is in viewport.

Sooo sorry for the bug.

**Comment by israeloriente** [comment]
> @Bilelkabtni I found the solution, please set `lazy: false`

It's work!!!!
Example:
    <circle-progress
    [percent]="Teste"
    [radius]="55"
    [showZeroOuterStroke]="true"
    [lazy]="false">
  </circle-progress>

**Comment by Evanc123** [comment]
Had the exact same problem. Fixed with Lazy: false

**Comment by samgevorgyan** [comment]
I want to use [lazy] : true   and the same time load  progress bar automaticly when I will scroll.

please fix it

**Comment by dineshghule321** [comment]
Had the exact same problem on google chrome latest version. Fixed with Lazy: false
@iPazooki   , it works for me , thank you :)

**Comment by Bedo81** [comment]
For me this issue happens only when I use onPush change detection strategy. But [lazy]="false" fixes it.

**Comment by drkhannah** [comment]
the only way i can get it to show up on page load is to set `animation: false`

**Comment by ramilcatalandomingo** [comment]
I am using `Ionic 5 with Capacitor` and when my app goes to the background and then the foreground, the progress bar does not move anymore. Even if I set the `lazy: false` or `animation: false` it does not work.

**Comment by cseas** [comment]
Having the same issue. Need to set `animation: false` for the correct percent value to load. Otherwise it gets stuck on a smaller value until I click on the title.
