### ISSUE TITLE
1.4.1 not worked in Ionic 4, but downgrade to 1.4.0 no issue

### ISSUE THREAD

**Issue by notalk0** [bootsoon/ng-circle-progress#87]
latest version 1.4.1 not worked in Ionic 4, but downgrade to 1.4.0 no issue.

**home.component.html**
```
<circle-progress 
[percent]="85"    ---> i define 85%, but when page loaded it show 0% (binding variable in ts also same get 0%)
[radius]="100" 
[outerStrokeWidth]="16" 
[innerStrokeWidth]="8"
[outerStrokeColor]="'#78C000'" 
[innerStrokeColor]="'#C7E596'" 
[animation]="true" 
[animationDuration]="300">
</circle-progress>
```

![Capture](https://user-images.githubusercontent.com/9769260/58947337-49014e80-87ba-11e9-882c-1141fd31f378.JPG)

**Comment by DarkFluid** [comment]
I concluded that the percent only updates if renderOnClick is true and you click the bar.

**Comment by notalk0** [comment]
@DarkFluid Thanks for your guidance, actually I'm using ion-fab button trigger the timer rather than click on the bar. For my case put lazy: true in home.module.ts solve my problem

Reference:
#85 > @Bilelkabtni I found the solution, please set `lazy: false`
 

![Capture](https://user-images.githubusercontent.com/9769260/59018541-b1af0080-8878-11e9-96fb-b23f75f20d15.JPG)

**Comment by Bilelkabtni** [comment]
Thanks guys works fine for me too :)

**Comment by bootsoon** [comment]
`lazy` is a new feature introduced in 1.4.1. It's used to pause the circle when out of viewport. 

If everything is OK the circle progress bar should process whether or not `lazy` is true when `<svg>` tag is in viewport.

Sooo sorry for the bug.

**Comment by aardaipek** [comment]
Thanks for the solution. I could not see `[outerStrokeColor]` and `[innerStrokeColor]` on the my app.  `lazy= "false"` worked for me.

**Comment by kelanik8** [comment]
Thanks Very Much

**Comment by wmehanna** [comment]
thank you very much!
