### ISSUE TITLE
change color upon different percentages

### ISSUE THREAD

**Issue by jijishthomas** [bootsoon/ng-circle-progress#88]
Hii,
How can I change the circle color upon reaching different percentages.
i.e 
Red for <25
yellow <50
blue <75
green >75

**Comment by bootsoon** [comment]
```HTML
<!-- app.component.html -->
<circle-progress [options]="ngCircleOptions"></circle-progress>
```

```TypeScript

// app.component.js

import { Component, ViewChild } from '@angular/core';
import { CircleProgressComponent } from 'ng-circle-progress';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html'
})
export class AppComponent {

  @ViewChild('circleProgress') circleProgress: CircleProgressComponent;

  ngCircleOptions = {
    percent: 85,
    radius: 60,
    showBackground: false,
    outerStrokeWidth: 10,
    innerStrokeWidth: 5,
    startFromZero: false,
    outerStrokeColor: null,
    showSubtitle: false,
    subtitleFormat: (percent: number): string => {
      if(percent < 25){
        this.ngCircleOptions.outerStrokeColor = "red";
      }else if(percent < 50){
        this.ngCircleOptions.outerStrokeColor = "yellow";
      }else if(percent < 75){
        this.ngCircleOptions.outerStrokeColor = "blue";
      }else{
        this.ngCircleOptions.outerStrokeColor = "green";
      }
      return '';
    }
  }

}

```

**Comment by jijishthomas** [comment]
> ```
> 
> <circle-progress [options]="ngCircleOptions"></circle-progress>
> ```
> 
> ```ts
> // app.component.js
> 
> import { Component, ViewChild } from '@angular/core';
> import { CircleProgressComponent } from 'ng-circle-progress';
> 
> @Component({
>   selector: 'app-root',
>   templateUrl: './app.component.html'
> })
> export class AppComponent {
> 
>   @ViewChild('circleProgress') circleProgress: CircleProgressComponent;
> 
>   ngCircleOptions = {
>     percent: 85,
>     radius: 60,
>     showBackground: false,
>     outerStrokeWidth: 10,
>     innerStrokeWidth: 5,
>     startFromZero: false,
>     outerStrokeColor: null,
>     showSubtitle: false,
>     subtitleFormat: (percent: number): string => {
>       if(percent < 25){
>         this.ngCircleOptions.outerStrokeColor = "red";
>       }else if(percent < 50){
>         this.ngCircleOptions.outerStrokeColor = "yellow";
>       }else if(percent < 75){
>         this.ngCircleOptions.outerStrokeColor = "blue";
>       }else{
>         this.ngCircleOptions.outerStrokeColor = "green";
>       }
>       return '';
>     }
>   }
> 
> }
> ```

thanks for the quick update!!

**Comment by jijishthomas** [comment]
> ```
> 
> <circle-progress [options]="ngCircleOptions"></circle-progress>
> ```
> 
> ```ts
> // app.component.js
> 
> import { Component, ViewChild } from '@angular/core';
> import { CircleProgressComponent } from 'ng-circle-progress';
> 
> @Component({
>   selector: 'app-root',
>   templateUrl: './app.component.html'
> })
> export class AppComponent {
> 
>   @ViewChild('circleProgress') circleProgress: CircleProgressComponent;
> 
>   ngCircleOptions = {
>     percent: 85,
>     radius: 60,
>     showBackground: false,
>     outerStrokeWidth: 10,
>     innerStrokeWidth: 5,
>     startFromZero: false,
>     outerStrokeColor: null,
>     showSubtitle: false,
>     subtitleFormat: (percent: number): string => {
>       if(percent < 25){
>         this.ngCircleOptions.outerStrokeColor = "red";
>       }else if(percent < 50){
>         this.ngCircleOptions.outerStrokeColor = "yellow";
>       }else if(percent < 75){
>         this.ngCircleOptions.outerStrokeColor = "blue";
>       }else{
>         this.ngCircleOptions.outerStrokeColor = "green";
>       }
>       return '';
>     }
>   }
> 
> }
> ```
this is not working for me!
all other options provided in 'ngCircleOptions' are working but the 'ngCircleOptions.outerStrokeColor' isn't!

**Comment by JamboBuenna** [comment]
Any update on this, not working here either
