### ISSUE TITLE
Passing custom parameter to titleFormat

### ISSUE THREAD

**Issue by csimpi** [bootsoon/ng-circle-progress#89]
Hi, thanks for this awesome module!

I'm interested in how to pass additional parameters to the `titleFormat` callback function?
I would like to make a title like: 
`%visited/%total`

```
  formatTitle(title){
    console.log('formatTitle',title,this.progress);
    return this.progress.title+'/'+this.progress.total;
  }
```
`this.progress` is undefined, how can I pass it to the callback function?

Thank you,
Peter

**Comment by bootsoon** [comment]
```
// subtitleFormat callback example
formatSubtitle = (percent: number) : string => {
  if(percent >= 100){
    return "Congratulations!"
  }else if(percent >= 50){
    return "Half"
  }else if(percent > 0){
    return "Just began"
  }else {
    return "Not started"
  }
}
```

**Comment by csimpi** [comment]
@bootsoon Still don't know how to pass `this.progress` :)
