### ISSUE TITLE
Border radius for the image

### ISSUE THREAD

**Issue by candorthor** [bootsoon/ng-circle-progress#90]
Hi,

How can I set border-radius for the image in ng-circle-progress.
.html page
```
<circle-progress
                    [percent]="80"
                    [radius]="30"
                    [outerStrokeWidth]="8"
                    [innerStrokeWidth]="0"
                    [outerStrokeColor]="'#FF0000'"
                    [innerStrokeColor]="'#800000'"
                    [animation]="true"
                    [animationDuration]="400"
                    [imageSrc]="'/assets/images/music.png'"
                    [showImage]="true"
                    [imageHeight]="60"
                    [imageWidth]="60"
></circle-progress>
```
I want the image src in html itself.  Could you please help me in this.

**Comment by candorthor** [comment]
@bootsoon 

Could you please help in this?

**Comment by bootsoon** [comment]
There's no border-radius for image tag in circle-progress.

**Comment by candorthor** [comment]
@bootsoon 

Okay, then how can I place the image exactly inside the progress ring. 
The image is in rectangle shape, but I need the image to be appended inside the progress circle with round in shape.

Image is attached.

Screenshot
![image](https://user-images.githubusercontent.com/49184671/62311124-b83cab80-b4a8-11e9-933a-11cc237cf399.png)

**Comment by candorthor** [comment]
@bootsoon 

Any updates?

**Comment by bootsoon** [comment]
https://stackoverflow.com/questions/7430580/setting-rounded-corners-for-svgimage

'border-radius' does not apply to svg:image element. The simplest simplest way is choosing an image with circle-round shape. e.g. 
![image](https://user-images.githubusercontent.com/20899374/62380550-0373be80-b57c-11e9-91b0-2191776068d2.png)

**Comment by candorthor** [comment]
@bootsoon 

Yes, I know circular image can be choosen. But I don't want circular shape image to be appended. I want rectangular shape image appended with circular in shape.
It would be great if you help me in solving the this issue

**Comment by candorthor** [comment]
@bootsoon 

Any updates?

**Comment by bootsoon** [comment]
'border-radius' does not apply to svg:image element.

We can use 'clip-path' like this:

```
<defs>
    <rect id="rect" x="25%" y="25%" width="50%" height="50%" rx="15"/>
    <clipPath id="clip">
      <use xlink:href="#rect"/>
    </clipPath>
</defs>

<use xlink:href="#rect" stroke-width="2" stroke="black"/>
<image xlink:href="boston.jpg" width="100%" height="100%" clip-path="url(#clip)"/>
```

**Comment by candorthor** [comment]
@bootsoon 

How can I integrate it to my code?

**Comment by bootsoon** [comment]
Fork it.

**Comment by candorthor** [comment]
@bootsoon 

Sorry, I didn't get you. Could you please elaborate it

**Comment by Eraldo** [comment]
Too bad I would have also wanted this feature. :|

**Comment by candorthor** [comment]
Hi @Eraldo 

I have replied it in [Rounded image #94](https://github.com/bootsoon/ng-circle-progress/issues/94).
Could you please look into it and check whether it works or not.
