### ISSUE TITLE
animation not working 

### ISSUE THREAD

**Issue by karuppasamy20** [bootsoon/ng-circle-progress#92]
<circle-progress [percent]="getData(data[col.field])" [radius]="35" [subtitle]="data['progress']"
                [outerStrokeWidth]="4" [innerStrokeWidth]="2" [unitsFontSize]="'8'" [titleFontSize]="'8'"
                [titleColor]="'#179781'" [unitsColor]="'#179781'"
                [outerStrokeColor]="'#78C000'" [innerStrokeColor]="'#C7E596'"
                [animation]="true" [animationDuration]="300"></circle-progress>

**Comment by karuppasamy20** [comment]
![Firefox_Screenshot_2019-08-08T05-06-45 165Z](https://user-images.githubusercontent.com/26301377/62676601-08e06700-b9c9-11e9-9b37-04234776fc6b.png)

**Comment by bootsoon** [comment]
It's a bug in 1.4.1. Please set lazy to false.
