### ISSUE TITLE
Negative Percentage

### ISSUE THREAD

**Issue by ammirante** [bootsoon/ng-circle-progress#93]
I tried to put some negative value but apparently it's not possible yet, correct? Is there any way to do this?

**Comment by bootsoon** [comment]
https://github.com/bootsoon/ng-circle-progress/blob/4985892f13efdcb43e81507344f714400d236712/src/circle-progress.component.ts#L331

No, It's not possible to put some negative value.

**Comment by ammirante** [comment]
Ok, thank you so much
