### ISSUE TITLE
Rounded image

### ISSUE THREAD

**Issue by Eraldo** [bootsoon/ng-circle-progress#94]
I would like the image to fit inside the progress circle which currently does not happen with square images that are bigger than the progress circle.
Especially for responsive sizes I think this is important since the image will always be as big as possible. (100% height and width).

A solution idea was provided already: #90

**Comment by candorthor** [comment]
@Eraldo 
Add the below CSS

```
svg image {
  clip-path: circle(49%);
}
```

It worked for me

**Comment by LeonardoPalomo** [comment]
Sadly, this did not work for me

**Comment by LeonardoPalomo** [comment]
I had to add `::ng-deep` for this to work.

`::ng-deep svg image {
      clip-path: circle(49%);   
}`
