### ISSUE TITLE
Animation not working Angular 8

### ISSUE THREAD

**Issue by mbayones** [bootsoon/ng-circle-progress#96]
Hello, im trying to implement it but the animation only works if scrolling on the page. If not, goes from 0 to 72 (in this case) in the time i set but not showing in an animated way.

I have tried to force it by this.progress.animate(0,100) on the ngOnInit() but got same result.
Im using Angular 8.
Thanks in advance.

<circle-progress #progress
                                                      [percent]="72"
                                                      [radius]="35"
                                                      [outerStrokeWidth]="9"
                                                      [innerStrokeWidth]="8"
                                                      [outerStrokeColor]="'#78C000'"
                                                      [innerStrokeColor]="'#C7E596'"
                                                      [animation]="true"
                                                      [animationDuration]="1000"
                                                      [outerStrokeWidth]="10"
                                                      [innerStrokeWidth]="10"
                                                      [space] = "-10"
                                                      [imageHeight]="26"
                                                      [imageWidth]="26"
                                                      [showUnits]="false"
                                                      [subtitle]="'Impo'"
                                                      [startFromZero]="false"
                                                      [responsive]="true"
                                                      [lazy]="false"
                                                      [animation]="'easeInOutQuart'"
                                                    ></circle-progress>

**Comment by mbayones** [comment]
My fault, changeDetection: ChangeDetectionStrategy.OnPush was set on @Component.-

**Comment by ddtch** [comment]
@mbayones and why it should break animation? In my case somehow circle does not show correct percentage value, and there is no animation.
