### ISSUE TITLE
1.5.0 breaks when rendering on the server

### ISSUE THREAD

**Issue by danieldanielecki** [bootsoon/ng-circle-progress#97]
After updating from `1.4.1` to `1.5.0` an application breaks with the following error `ReferenceError: Document is not defined`. Tested when deploying to Firebase when using Cloud Functions for Firebase for Server-Side Rendering (SSR) based on Angular Universal.

**Comment by omahjoub** [comment]
Had the same error on my project when moving from `1.4.1 `to `1.5.0`: 
```
xxx/dist/server/main.js:88677 Object(tslib__WEBPACK_IMPORTED_MODULE_0__["__metadata"])
("design:paramtypes", [CircleProgressOptions, 
_angular_core__WEBPACK_IMPORTED_MODULE_1__["ElementRef"], Document])

ReferenceError: Document is not defined at Module.B0QU (xxxdist/server/main.js:88677:165)
```

**Comment by ehsanagh** [comment]
I have the same problem, any Idea or workaround about this .

**Comment by ehsanagh** [comment]
I fixed the problem, I'll send the pull request soon.

**Comment by ehsanagh** [comment]
I sent the pull request, @bootsoon please merge this.

**Comment by ehsanagh** [comment]
Hi, this issue fixed and merged, Thank you @bootsoon

**Comment by omahjoub** [comment]
@bootsoon should we hope any release soon that fixes this?
Thx.

**Comment by bootsoon** [comment]
1.5.1 has been released.
