### ISSUE TITLE
why render doesnot work well. 

### ISSUE THREAD

**Issue by Foolegend** [bootsoon/ng-circle-progress#98]
I have 5 circeprogress components.  only the first will render process from 0 to 100,the left 4 components does not work, theire percenets always stay 0.
my codes bellow:
<mat-sidenav-content fxFlexFill>
    <mat-tab-group >
        <mat-tab *ngFor="let types of typesOfModule;let i=index" label="{{moduleNames[i]}}"> 
            <div class="left">
                    <circle-progress [percent]="getShowPercent(i)"
                    [subtitle]="getCircleSubtitle(i)">
                    </circle-progress>
                    <div class="form-group">
                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="taskid" placeholder="必须给下载任务起一个任务号" [(ngModel)]="tasks[i]">
                        </div>  
                        <button class="btn btn-default" (click)="download(i)">下载</button> 
                    </div>
            </div>
            <div class="right">
                <mat-selection-list [(ngModel)]="selectedOptionsModule[i]">
                        <mat-list-option *ngFor="let type of types" [value]="type">
                             {{moduleTypeMap[type]}}
                        </mat-list-option>
                </mat-selection-list>              
            </div>    
        </mat-tab>
    </mat-tab-group>

**Comment by Foolegend** [comment]
when I click the left 4 circleprogress,the process up to 100 suddenly. But it doesnot auto render by itself.why?

**Comment by Foolegend** [comment]
this question has been sovled by update ng-circle-progress to version 1.5.0.

**Comment by ChiKaLiO** [comment]
> this question has been sovled by update ng-circle-progress to version 1.5.0.

same problem on 1.7.1
